config/routes.rb
Rails.application.routes.draw do

  get '/users/nasa', to: "users#nasa", as: 'nasa' 
  # ruta para jugar, botón amarillo
  get '/users/play', to: "users#play", as: 'play'
  # deslogearse de la pagina
  delete '/logout', to: 'users#destroy', as: "logout"

  #boton dejar mensaje
  get "/messages/new", to: 'messages#new', as: 'messages_new'
  # boton hacer pago
  post '/messages/barcode', to: 'messages#barcode', as: 'barcode'
  # hacer llamada a openpay
  post '/messages/charges', to: 'messages#charges', as: 'charges'
  # metodo activado al dar click en boton rojo open pay
  get "/messages/openpay", to: 'messages#openpay', as: 'messages_openpay'

  post '/messages/search', to: "messages#search", as: 'messages_search'

  post '/users/user_log', to: "users#user_log", as: 'user_log'
  get '/users/log', to: "users#log", as: 'log'

  get '/users/new'
  post '/users/create', to: "users#create", as: 'user_create'

  get 'users/index'
  get 'messages/index'

  root 'users#index'
  get 'tags/index'


  resources :users
  resources :tags
  resources :messages
      #   Prefix Verb   URI Pattern                  Controller#Action
      # users_index GET    /users/index(.:format)       users#index

      # tags_index GET    /tags/index(.:format)        tags#index
      #  users GET    /users(.:format)             users#index
      #        POST   /users(.:format)             users#create
      # new_user GET    /users/new(.:format)         users#new
      # edit_user GET    /users/:id/edit(.:format)    users#edit
      #   user GET    /users/:id(.:format)         users#show
      #        PATCH  /users/:id(.:format)         users#update
      #        PUT    /users/:id(.:format)         users#update
      #        DELETE /users/:id(.:format)         users#destroy



      #   tags GET    /tags(.:format)              tags#index
      #        POST   /tags(.:format)              tags#create
      # new_tag GET    /tags/new(.:format)          tags#new
      # edit_tag GET    /tags/:id/edit(.:format)     tags#edit
      #    tag GET    /tags/:id(.:format)          tags#show
      #        PATCH  /tags/:id(.:format)          tags#update
      #        PUT    /tags/:id(.:format)          tags#update
      #        DELETE /tags/:id(.:format)          tags#destroy


      # messages GET    /messages(.:format)          messages#index
      #        POST   /messages(.:format)          messages#create
      # new_message GET    /messages/new(.:format)      messages#new
      # edit_message GET    /messages/:id/edit(.:format) messages#edit
      # message GET    /messages/:id(.:format)      messages#show
      #        PATCH  /messages/:id(.:format)      messages#update
      #        PUT    /messages/:id(.:format)      messages#update
      #        DELETE /messages/:id(.:format)      messages#destroy

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :message_tags
  has_many :tags, through: :message_tags
  before_save { self.autor = autor.downcase}
  before_save { self.title = title.downcase}
  before_save { self.text = text.downcase}

end

app/controllers/messages_controller.rb
require 'openpay'
class MessagesController < ApplicationController
  def new
    p "*" * 50
    p "new mesage"
  end

  def charges
    # Objeto de open open pay con llaves publica y privada
    @openpay=OpenpayApi.new("mzdtln0bmtms6o3kck8f","sk_e568c42a6c384b7ab02cd47d2e407cab")
    #crear el recurso "cargos" con la fabrica de meotodos de open pay
    @charges=@openpay.create(:charges)
    # se agregan su datos de llamada
    request_hash={
         "method" => "store",
         "amount" => params[:charges][:amount],
         "description" => "Cargo con tienda"
       }
    # se obtiene la respuesta en un hash (también se puede hacer con objetos JSON)
    response_hash=@charges.create(request_hash.to_hash)
    # agregar a una variable global para poder verlos en la modal
    @resp = response_hash
    # p "*" * 50
  end

  def openpay
    # p "_" * 50
    # p "openpay"
    # #merchant and private key
    # merchant_id='mywvupjjs9xdnryxtplq'
    # private_key='sk_92b25d3baec149e6b428d81abfe37006'
    # #An openpay resource factory instance is created out of the OpenpayApi
    # openpay=OpenpayApi.new(merchant_id,private_key)
    # # The openpay factory instance is in charge to generate the required resources through a factory method (create)
    # p charges=openpay.create(:charges)
    # p "_" * 50
  end

  def index
    # p "-" * 50
    # p "index de mensajes"
    # p session[:user_id]
    @messages = Message.all
  end

  # este method responde a la ruta "/messages"
  def create
    # "message"=>{"title"=>"", "text"=>"", "tag"=>""},
    title = params[:message][:title]
    text = params[:message][:text]
    input_in_the_form = params[:message][:tag]
    autor = User.find(session[:user_id].to_i).name
    m = Message.create(title: title, text: text, autor: autor)
    if input_in_the_form != ""
      input_in_the_form.downcase!
			# separate the input throw a regex with comas, ignoring black spaces and put in a Ary
			ary_whit_input = input_in_the_form.split (/\s*,\s*/)
      ary_whit_input.uniq!
			# itarate throw the ary
			ary_whit_input.each do |tag_name|
				# find if the tag already exists
				tag = Tag.find_by(name: tag_name)
				# if not already exists
				if tag.blank?
					# create a new tag
					tag = Tag.create(name: tag_name)
          MessageTag.create(message_id: m.id, tag_id: tag.id)
        else
          MessageTag.create(message_id: m.id, tag_id: tag.id)
				end
			end
    end
    @messages= Message.all

  end
  
  def search
    # p "_" * 50
    # p "messages_search"
    # asignar el parametro del formulario
    @word = params[:search][:word]
    # a menos que el parametro venga en blanco, convertir el string en minuscula
    @word.downcase! unless @word == ""
    # buscaar aquellos donde el títulos es igual a la palabra buscada
    @mtitle = Message.where(title: @word)
    # invertir orden de mensajes, no, estaba buscando todos originalemente, sólo los del seed, asi que usamos está solución,
    mensajes = Message.all.reverse
    # hacer un ary vacio
    @mtext = []
    # mapear los mensajes
    mensajes.map do|m|
      # separar por palabra el text, en una array
      text =  m.text.scan(/\w+/)
      # iterar en cada texto
      text.each do |t|
        #  si alguna palabra es igual a uno de los elementos del text, empujar id a la variable de instance
         @mtext << Message.where(id: m.id) if t == @word
      end
    end
    # unifocar todos los arys en un solo nivel
     @mtext.flatten!

    # buscaar aquellos donde el autor es igual a la palabra buscada
    @mautor = Message.where(autor: @word)
    # buscaar aquellos donde el nombre es igual a la palabra buscada
    @tname = Tag.where(name: @word)

    p "_" * 50
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_buttons.html.erb
<div class="wrap">
  <div class="content ">
<%= button_to "Dejar mensaje", messages_new_path ,class: "btn btn-success",id: "btn_user_new",:method => :get ,remote: true %>
<br>

<%= button_to "Jugar", play_path , class: "btn btn-warning" ,:method => :get, remote: true %>
<br>
<%= button_to "Nasa", nasa_path , class: "btn btn-info" ,:method => :get, remote: true %>

<%= button_to "Donar dinero a Ivan", messages_openpay_path,id: "btn-openPay", class: "btn btn-info" ,:method => :get, remote: true %>


<br>

       <%= form_for :search, :html => {class: "form-search" } , remote: true, url: messages_search_path do |f| %>
       <i class="fa fa-search"></i>
         <%= f.text_field :word , placeholder: "Estoy buscando..." %>
       <%= f.submit "Buscar", class: "button"%>

       <% end %>
<br>

  </div>
</div>

app/views/messages/_index.html.erb
<%= button_to "dejar mensaje", messages_new_path ,class: "btn btn-success",id: "btn_user_new",:method => :get ,remote: true %>
<div class="wrap-form">
   <div class="content-form">
   <br>
   <h3>Obtener linea de pago de Open Pay en tienda</h3>
   <%= button_to "Obtener codigo", messages_openpay_path, class: "btn btn-danger" ,:method => :get, remote: true %>


   <h3>Busqueda por</h3>
   <%= form_for :search, remote: true, url: messages_search_path do |f| %>
   <p>
     <%= f.label :palabra %><br>
     <%= f.text_field :word %>
   </p>
   <p>
     <%= f.submit "buscar", class: "btn btn-info"%>
   </p>
   <% end %>


   </div>
</div>



<table class="table">
    <thead>
      <tr>
        <td>#</td>
        <th>Autor</th>
        <th>Titulo</th>
        <th>Texto</th>
        <th>Número de tags</th>
        <th>Tags</th>
      </tr>
    </thead>
    <tbody>
      <%@messages.reverse.each_with_index do |message, index|%>
        <%if index % 2 == 0%>
            <%clase = "inpar"%>
        <%else%>
            <%clase = "par"%>
        <%end%>
        <tr class="<%=clase%>">
          <td ><%=index += 1 %></td>
          <td><%=message.autor.capitalize%></td>
          <td><%=message.title.capitalize%></td>
          <td><%=message.text.capitalize%></td>
          <td><%=message.tags.count%></td>
          <td>
              <%message.tags.each do |t|%>
              <ul>
                <li><%=t.name.capitalize%></li>
              </ul>
              <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div id="search-modal" class="modal fade"></div>
<div id="openpay-modal" class="modal fade"></div>
<div id="master-modal" class="modal fade"></div>

app/views/messages/_messages.html.erb
<table class="table">
    <thead>
      <tr id="titles">
        <td>#</td>
        <th>Autor</th>
        <th>Titulo</th>
        <th>Texto</th>
        <th>Número de tags</th>
        <th>Tags</th>
      </tr>
    </thead>
    <tbody>
      <%@messages.reverse.each_with_index do |message, index|%>
        <%if index % 2 == 0%>
            <%clase = "inpar"%>
        <%else%>
            <%clase = "par"%>
        <%end%>
        <tr class="<%=clase%>">
          <td ><%=index += 1 %></td>
          <td><%=message.autor.capitalize%></td>
          <td><%=message.title.capitalize%></td>
          <td id="tabla_texto"><%=message.text.capitalize%></td>
          <td><%=message.tags.count%></td>
          <td>
              <%message.tags.each do |t|%>
              <ul>
                <li><%=t.name.capitalize%></li>
              </ul>
              <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/messages/_new.html.erb
<div class="wrap">
  <div class="content">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          Ingresa tu mensaje
        </div>
        <div class="modal-body">
          <%= form_for :message, url: messages_path, remote: true do |f| %>
          <p>
            <%= f.label :titulo %><br>
            <%= f.text_field :title %>
          </p>

          <p>
            <%= f.label :texto %><br>
            <%= f.text_area :text %>
          </p>
          <h4>Ingresa Etiqueta</h4>
          <p>Puede ingresar más de un tag, separandolos con comas ","</p>
          <p>Ejemplo: tag1, tag2, etc</p>
          <p>
            <%= f.label :tag %><br>
            <%= f.text_field :tag %>
          </p>
          <p>
            <%= f.submit "salvar mensaje", class: "btn btn-success"%>
          </p>
          <% end %>

          <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
          <br>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>

  </div>
</div>

app/views/messages/_openpay.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title">Ingresar monto</h3>
    </div>
      <div class="modal-body">

        <%unless params[:charges] %>

            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= form_for :charges, url: charges_path, remote: true do |f| %>

                <%= f.label :amount %>
                <%= f.number_field :amount, class: 'form-control' %>

                <br>
                <%= f.submit "Llamada a open pay", class: "btn btn-primary" %>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
                <% end %>

        <% end %>

      </div>
      <div class="modal-footer" id="openpay-m">

      </div>
  </div>
</div>

app/views/messages/_search.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title">Mensajes con la palabra clave: <%=@word%></h3>
    </div>
      <div class="modal-body">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        <br>

        <table class="table" id="modal-tabla">

          <% if @mtitle.count > 0%>
            <thead class="titulo">
              <tr >
                <th class="titulo">TÍTULO: <%=@word%> </th>
              </tr>
              <tr>
                <th>Titulo</th>
                <th>Texto</th>
                <th>Autor</th>

                <th>Tags</th>
              </tr>
            </thead>
            <tbody class="titulo">
                  <%@mtitle.each do |me|%>
                      <tr>
                        <td><%=me.title.capitalize%></td>
                        <td><%=me.text.capitalize%></td>
                        <td><%=me.autor.capitalize%></td>

                        <td>
                            <%me.tags.each do |t|%>
                            <ul>
                              <li><%=t.name.capitalize%></li>
                            </ul>
                            <%end%>
                        </td>
                      </tr>


                  <% end %>
          <% end%>


          <% if @mtext.count > 0%>
            <thead class="texto">
              <tr>
                  <th>TEXTO: <%=@word%> </th>
                  <tr>
                    <th>Titulo</th>
                    <th>Texto</th>
                    <th>Autor</th>

                    <th>Tags</th>
                  </tr>
              </tr>
            </thead>
            <tbody class="texto">
                  <%@mtext.each do |me|%>
                      <tr>
                        <td><%=me.title.capitalize%></td>
                        <td><%=me.text.capitalize%></td>
                        <td><%=me.autor.capitalize%></td>

                        <td>
                            <%me.tags.each do |t|%>
                            <ul>
                              <li><%=t.name.capitalize%></li>
                            </ul>
                            <%end%>
                        </td>
                      </tr>


                  <% end %>
          <% end%>



          <% if @mautor.count > 0%>
            <thead class="autor">
              <tr>
                  <th>AUTOR: <%=@word%> </th>
                  <tr>
                    <th>Titulo</th>
                    <th>Texto</th>
                    <th>Autor</th>

                    <th>Tags</th>
                  </tr>
              </tr>
            </thead>
            <tbody class="autor">
                  <%@mautor.each do |me|%>
                      <tr>
                        <td><%=me.title.capitalize%></td>
                        <td><%=me.text.capitalize%></td>
                        <td><%=me.autor.capitalize%></td>

                        <td>
                            <%me.tags.each do |t|%>
                            <ul>
                              <li><%=t.name.capitalize%></li>
                            </ul>
                            <%end%>
                        </td>
                      </tr>


                  <% end %>
          <% end%>



          <% if @tname.count > 0%>
            <thead class="tag">
              <tr>
                  <th>TAG: <%=@word%> </th>
                  <tr>
                    <th>Titulo</th>
                    <th>Texto</th>
                    <th>Autor</th>

                    <th>Tags</th>
                  </tr>
              </tr>
            </thead>
            <tbody class="tag">
                  <%@tname.each do |tn|%>
                      <%tn.messages.each do |m|%>
                      <tr>
                        <td><%=m.title.capitalize%></td>
                        <td><%=m.text.capitalize%></td>
                        <td><%=m.autor.capitalize%></td>
                        <td>
                            <%m.tags.each do |t|%>
                            <ul>
                              <li><%=t.name.capitalize%></li>
                            </ul>
                            <%end%>
                        </td>
                      </tr>
                      <%end%>

                  <% end %>
          <% end%>



            </tbody>
          </table>

      </div>
      <div class="modal-footer">
    </div>
  </div>
</div>

app/views/messages/charges.js.erb
$(document).ready(function() {
  // apuntar al div del foooter de la modal
  var footermod = $("#openpay-m");
  // limpiar el div
  footermod.html("");
  // anexar titulo y codigo de barras
  footermod.append("<h3>Codigo de Barras</h3>")
  footermod.append('<img src="https://sandbox-api.openpay.mx/barcode/000020TR5L8MHUTJTIOHTT1C1G0090002?width=1&height=45&text=false" alt="barcode" />');
  // si el servidor regresa una respuesta exitosa
  <%if @resp%>
      footermod.append("<h4>Datos de pago en transacción</h4>")


          // anexar llave y valor de hash retornado por Open Pay, los datos se separan en una tabla donde todo se muetra en el head de la misma
            footermod.append("<table class='table'><thead><% @resp.each do |k,v|%><tr><td><%=k%></td><td><%=v%></td></tr></thead><tbody><% end %></tbody></table>"
            );

  <% end %>


});

app/views/messages/create.js.erb
$('#messages').html('<%= j render("messages")  %>');
// ocultar la vista modal de registro
$("#master-modal").modal("hide");

app/views/messages/index.html.erb
<div class="wrap-form">
   <div class="content-form">
  <h3>Ingresa tu mensaje</h3>

   <%= form_for :message, url: messages_path do |f| %>
   <p>
     <%= f.label :titulo %><br>
     <%= f.text_field :title %>
   </p>

   <p>
     <%= f.label :texto %><br>
     <%= f.text_area :text %>
   </p>
   <h4>Ingresa Etiqueta</h4>
   <p>Puede ingresar más de un tag, separandolos con comas ","</p>
   <p>Ejemplo: tag1, tag2, etc</p>
   <p>
     <%= f.label :tag %><br>
     <%= f.text_field :tag %>
   </p>
   <p>
     <%= f.submit "salvar mensaje", class: "btn btn-success"%>
   </p>
   <% end %>
   <br>
   <h3>Obtener linea de pago de Open Pay en tienda</h3>
   <%= button_to "Obtener codigo", messages_openpay_path, class: "btn btn-danger" ,:method => :get, remote: true %>


   <h3>Busqueda por</h3>
   <%= form_for :search, remote: true, url: messages_search_path do |f| %>
   <p>
     <%= f.label :palabra %><br>
     <%= f.text_field :word %>
   </p>
   <p>
     <%= f.submit "buscar", class: "btn btn-info"%>
   </p>
   <% end %>


   </div>
</div>



<table class="table">
    <thead>
      <tr>
        <td>#</td>
        <th>Autor</th>
        <th>Titulo</th>
        <th>Texto</th>
        <th>Número de tags</th>
        <th>Tags</th>
      </tr>
    </thead>
    <tbody>
      <%@messages.reverse.each_with_index do |message, index|%>
        <%if index % 2 == 0%>
            <%clase = "inpar"%>
        <%else%>
            <%clase = "par"%>
        <%end%>
        <tr class="<%=clase%>">
          <td ><%=index += 1 %></td>
          <td><%=message.autor.capitalize%></td>
          <td><%=message.title.capitalize%></td>
          <td><%=message.text.capitalize%></td>
          <td><%=message.tags.count%></td>
          <td>
              <%message.tags.each do |t|%>
              <ul>
                <li><%=t.name.capitalize%></li>
              </ul>
              <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div id="search-modal" class="modal fade"></div>
<div id="openpay-modal" class="modal fade"></div>

app/views/messages/new.js.erb
$("#master-modal").html("<%= escape_javascript(render 'new') %>");
$("#master-modal").modal("show");

app/views/messages/openpay.js.erb
$("#openpay-modal").html("<%= escape_javascript(render 'openpay') %>");
$("#openpay-modal").modal("show");

app/views/messages/search.js.erb
$("#search-modal").html("<%= escape_javascript(render 'search') %>");
$("#search-modal").modal("show");