config/routes.rb
Rails.application.routes.draw do

  get '/users/nasa', to: "users#nasa", as: 'nasa' 
  # ruta para jugar, botón amarillo
  get '/users/play', to: "users#play", as: 'play'
  # deslogearse de la pagina
  delete '/logout', to: 'users#destroy', as: "logout"

  #boton dejar mensaje
  get "/messages/new", to: 'messages#new', as: 'messages_new'
  # boton hacer pago
  post '/messages/barcode', to: 'messages#barcode', as: 'barcode'
  # hacer llamada a openpay
  post '/messages/charges', to: 'messages#charges', as: 'charges'
  # metodo activado al dar click en boton rojo open pay
  get "/messages/openpay", to: 'messages#openpay', as: 'messages_openpay'

  post '/messages/search', to: "messages#search", as: 'messages_search'

  post '/users/user_log', to: "users#user_log", as: 'user_log'
  get '/users/log', to: "users#log", as: 'log'

  get '/users/new'
  post '/users/create', to: "users#create", as: 'user_create'

  get 'users/index'
  get 'messages/index'

  root 'users#index'
  get 'tags/index'


  resources :users
  resources :tags
  resources :messages
      #   Prefix Verb   URI Pattern                  Controller#Action
      # users_index GET    /users/index(.:format)       users#index

      # tags_index GET    /tags/index(.:format)        tags#index
      #  users GET    /users(.:format)             users#index
      #        POST   /users(.:format)             users#create
      # new_user GET    /users/new(.:format)         users#new
      # edit_user GET    /users/:id/edit(.:format)    users#edit
      #   user GET    /users/:id(.:format)         users#show
      #        PATCH  /users/:id(.:format)         users#update
      #        PUT    /users/:id(.:format)         users#update
      #        DELETE /users/:id(.:format)         users#destroy



      #   tags GET    /tags(.:format)              tags#index
      #        POST   /tags(.:format)              tags#create
      # new_tag GET    /tags/new(.:format)          tags#new
      # edit_tag GET    /tags/:id/edit(.:format)     tags#edit
      #    tag GET    /tags/:id(.:format)          tags#show
      #        PATCH  /tags/:id(.:format)          tags#update
      #        PUT    /tags/:id(.:format)          tags#update
      #        DELETE /tags/:id(.:format)          tags#destroy


      # messages GET    /messages(.:format)          messages#index
      #        POST   /messages(.:format)          messages#create
      # new_message GET    /messages/new(.:format)      messages#new
      # edit_message GET    /messages/:id/edit(.:format) messages#edit
      # message GET    /messages/:id(.:format)      messages#show
      #        PATCH  /messages/:id(.:format)      messages#update
      #        PUT    /messages/:id(.:format)      messages#update
      #        DELETE /messages/:id(.:format)      messages#destroy

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :messages, dependent: :destroy#If you delete an article, its associated comments will also need to be deleted, otherwise they would simply occupy space in the database. Rails allows you to use the dependent option of an association to achieve this.
  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
    validates :name, presence: true, length: { maximum: 50 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
   validates :email, presence:   true, length: { maximum: 255 },
                     format:     { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  # validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def play
    p "-" * 50 
    p "play"
  end

  def index
    @messages= Message.all
    # si en las cokies no hay un user id
    if session[:user_id] != nil
      # si el id de usuario es un numero
      if session[:user_id].integer?
        # es posible que hya que CAMBIAR esta parte, ignoramos si otras paginas usan user id
        @user = User.find(session[:user_id].to_i)
        user_log
      end
    end
  end
  # meotodo al dar click en sign up
  def new
  end

  # metodo en vista modal
  def create
  # {"name"=>"", "email"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create my account"}
  #<ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"wAWOEwMiUn2Gt+3ELnAOe7CcP6O8xXGIVuuhBtAv54JRidGGy0/vpsP9uGQQJHHionyDLkodThtBMf//3vYk0g==", "user"=>{"name"=>"", "email"=>"", "password"=>"", "password_confirmation"=>""}, "commit"=>"Create my account", "controller"=>"users", "action"=>"create"} permitted: false>
  # name: params[:user][:name],
  # email: params[:user][:email],
  # password: params[:user][:password],
  # password_confirmation:[:user][:password_confirmation]
    @user = User.new(name: params[:user][:name], email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation] )

    if @user.save || @errors != nil
      session[:user_id] = @user.id
      @messages= Message.all
      # render 'messages/index'
      p "-" * 50
      p "salvo"
    else
      # @errors = @user.errors.full_messages
      # render "users/index"
      p "-" * 50
      p "no salvo"
    end

  end
  # al recargar la vista de mensajes
  def show
    # p "- " * 50
    # if @errors != nil
       @messages= Message.all
       render 'messages/index'
    #   # p session[:user_id] = User.last
    #   p "- " * 50
    # else
      # render "users/index"
    # end
  end

  def user_log
    if @user.nil?
      # encontrar primer usuario que cumple email y password
      @user = User.where(email: params[:user][:email], password: params[:user][:password] ).first
      if @user != nil
        session[:user_id] = User.where(email: params[:user][:email], password: params[:user][:password] ).first.id
        @messages= Message.all
      end
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
# deslogear el usario, este metodo es llamado desde el user controller
  def log_out
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    session.delete(:user_id)
    @user = nil
  end
end

app/views/users/_index.js.erb
$(document).ready(function(){
  var g = $('.gif');
  var times = 0
  var speed = 1500
  var arr = $('.arriba');
  var reg = $(".registro")
  var opa = .25

  // definicion funcion para que el gif aparesca y desparesca
  function moveButons() {
    $(arr).animate({
      height: "toggle",
    }, 1000, function() {
      // Animation complete.
    });
    $(reg).animate({
      opacity: opa,
      left: "-=100",
      // height: "toggle",
    }, speed, function() {
      // Animation complete.
    });
    opa = opa + opa;
    speed = speed - 100;
    $(arr).animate({
      height: "toggle",
    }, speed, function() {
      // Animation complete.
    });
    $(reg).animate({
      opacity: opa,
      left: "+=200",
      // height: "toggle",
    }, speed, function() {
      // Animation complete.
    });;
    opa = opa + opa;
    speed = speed - 100;
    $(arr).animate({
      height: "toggle",
    }, speed, function() {
      // Animation complete.
    });
    $(reg).animate({
      opacity: opa,
      left: "-=200",
      // height: "toggle",
    }, speed, function() {
      // Animation complete.
    })
    opa = opa + opa;
    speed = speed - 100;
    $(arr).animate({
      height: "toggle",
    }, speed, function() {
      // Animation complete.
    });
    $(reg).animate({
      opacity: opa,
      left: "+=100",
      // height: "toggle",
    }, speed, function() {
      // Animation complete.
    });;
    $(arr).animate({
      height: "toggle",
    }, speed, function() {
      // Animation complete.
    });


    times++;
    if (times<=0) {
      moveButons();
      // speed = speed - 753;
      console.log(speed);
    }
  };

  window.fbAsyncInit = function() {

     FB.init({
       appId      : '738636399658119',
       cookie     : true,
       xfbml      : true,
       version    : 'v2.10'
     });

    FB.getLoginStatus(function(response) {
      if (response.status === 'connected') {
        console.log('Logged in.');
        statusChangeCallback(response);
        console.log(response);
      }
      else {
        // console.log("no logged");
        // FB.login();
      }
    });

    // Person is now logged out
    // FB.logout(function(response) {
    // });

  //  FB.AppEvents.logPageView();
 };

 (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  // hechar a andar funcion
  // DESCOMENTAR para hacer funcionar la animacion
  // moveButons();


  // si hay un user loged
  if ("<%=session[:user_id]%>") {
    // mostrar mensajes y botones
    $("#messages").show();
    $("#buttons").show();
    $("#salir").show();

    // ocultar la vista modal de registro
    $("#log-modal").modal("hide");
    // ocultar botones de login y signup y fb
    $("#access").hide();
  }
});

app/views/users/_log.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title">Login</h3>
    </div>
      <div class="modal-body">
        <ul class="errors">
        </ul>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for :user, url: user_log_path do |f| %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <br>
            <%= f.submit "Buscarme", class: "btn btn-primary" %>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
            <% end %>

      </div>
      <div class="modal-footer">
    </div>
  </div>
</div>

app/views/users/_nasa.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <h3 class="modal-title">Nasa</h3>
    </div>

      <div class="modal-body">

        <div class="nasa">
          <!-- Url de la api -->
          <!-- <b>API URL:</b>
          <pre id="reqObject"></pre> -->

          <img id="apod_img_id" width="250px"/>

          <iframe id="apod_vid_id" type="text/html" width="640" height="385" frameborder="0"></iframe>
          <!-- <p id="copyright"></p> -->

          <h3 id="apod_title"></h3>
          <p id="apod_explaination"></p>
          <br/>
          <!-- Objeto js -->
          <!-- <b>Return Object:</b>
          <pre id="returnObject"></pre> -->
        </div>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
     </div>
  </div>
</div>

app/views/users/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title">Tus datos</h3>
    </div>
      <div class="modal-body">
        <ul class="errors">
        </ul>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for :user, url: user_create_path do |f| %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <br>
            <%= f.submit "Create my account", class: "btn btn-primary" %>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
            <% end %>

      </div>
      <div class="modal-footer">
    </div>
  </div>
</div>

app/views/users/_play.html.erb
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <h3 class="modal-title">Play</h3>
    </div>

      <div class="modal-body">

        <canvas id="myCanvas" ></canvas>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>

     </div>
  </div>
</div>

app/views/users/create.js.erb
// limpiar lista de errores
$("ul.errors").html("")
// si hay errores de validacion
<% if @user.errors.any? %>
  // cada uno de los errores
  <% @user.errors.full_messages.each do |e| %>
  // anexarlos a la lista en la vista parcial
    $(".errors").append("<li> <%= e %> </li>")
  <% end %>
  // si no hay errores
<% else %>
  // mostrar mensajes
  $("#messages").show();
  $("#buttons").show();
  $("#salir").show();
  // ocultar la vista modal de registro
  $("#user-modal").modal("hide")
  // ocultar botones de login y signup y fb
  $("#access").hide();
<% end %>

app/views/users/index.html.erb
      <!-- <br>
      <div class="wrap">
      </div> -->
      <div class="wrap">
        <div class="content ">
          <div class="arriba">
            <!-- la clase "arriba" sirve para hacer la animaciòn en espiral de inicio-->
          </div>
          <br>

          <div id="access">
            <div class="registro">
              <%= button_to "Registrarse", new_user_path,class: "btn btn-success",id: "btn_user_new",:method => :get ,remote: true %>
            </div>
            <div class="registro">
              <br>
              <%= button_to "Logearse", log_path ,class: "btn btn-info",:method => :get ,remote: true %>
              <br>
            </div>
            <br>
            <div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="true"></div>
            <br>
            <br>
            <div
              class="fb-like"
              data-share="true"
              data-width="250"
              data-show-faces="true">
            </div>

          </div>


          <div id="buttons">
              <%= render 'messages/buttons'%>              
          </div>
          <div id="messages">
              <%= render 'messages/messages'%>
          </div>
          <!-- <div class="gif">
            <%=image_tag("09.gif", alt: "no se ve imagen")%>
          </div> -->
      </div>
    </div>
    <!-- vistas modales -->
    <div id="user-modal" class="modal fade"></div>
    <div id="log-modal" class="modal fade"></div>
    <div id="search-modal" class="modal fade"></div>
    <div id="openpay-modal" class="modal fade"></div>
    <div id="master-modal" class="modal fade"></div>

    <script>
      <%= render :partial => 'users/index.js'%>
    </script>

app/views/users/log.js.erb
$("#log-modal").html("<%= escape_javascript(render 'log') %>");
$("#log-modal").modal("show");

app/views/users/nasa.js.erb
$("#master-modal").html("<%= escape_javascript(render 'nasa') %>");
$("#master-modal").modal("show");

var url = "https://api.nasa.gov/planetary/apod?api_key=qoxy2FMZzOFN6gw3JoQoDytVP0huYMsfzlgh7kQr";
// Nasa APPI
$.ajax({
  url: url,
  success: function(result){
  if("copyright" in result) {
    $("#copyright").text("Image Credits: " + result.copyright);
  }
  else {
    $("#copyright").text("Image Credits: " + "Public Domain");
  }

  if(result.media_type == "video") {
    $("#apod_img_id").css("display", "none");
    $("#apod_vid_id").attr("src", result.url);
  }
  else {
    $("#apod_vid_id").css("display", "none");
    $("#apod_img_id").attr("src", result.url);
  }
  $("#reqObject").text(url);
  $("#returnObject").text(JSON.stringify(result, null, 4));
  $("#apod_explaination").text(result.explanation);
  $("#apod_title").text(result.title);
}
});

app/views/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>");
$("#user-modal").modal("show");

app/views/users/play.js.erb
$("#master-modal").html("<%= escape_javascript(render 'play') %>");
$("#master-modal").modal("show");

//-------VARIABLES
function game(){
  var jugar = 0
  // variable con lienzo
  var canvas = document.getElementById("myCanvas");

  // dimenciones de http://htmlcheats.com/html/resize-the-html5-canvas-dyamically/
  // width="480" height="320"
  // el ancho es equivalente al grueso del la vista modal
  canvas.width = $(".modal-body").width();
  canvas.height = 320;
  // The getContext() method returns an object that provides methods and properties for drawing on the canvas. the getContext("2d") object, which can be used to draw text, lines, boxes, circles, and more - on the canvas.
  //ctx: It is a shorthand for the word "context"
  var ctx = canvas.getContext("2d");

  //definiremos un punto de inicio en la parte central inferior del lienzo en las variables llamadas x e y, a continuación, las utilizaremos para definir la posición en la que se dibuja el círculo.
  var x = canvas.width/2;
  var y = canvas.height-30;
  // añadir un valor pequeño a "x" e "y" después de que cada fotograma se haya dibujado para que parezca que la pelota se está moviendo. Definamos estos valores pequeños como dx y dy, y establezcamos sus valores en 2 y -2 respectivamente
  var dx = 2;
  var dy = -2;

  // Para facilitar los cálculos, definamos una variable llamada ballRadius que mantendrá el radio del círculo dibujado y se utilizará para los cálculos.
  var ballRadius = 10;

  //  paleta para golpear la bola, paddleHeight servirá para definir la altura de la paleta, paddleWidth la anchura y paddleX la posición en el eje X en la que empieza a dibujarse.
  var paddleHeight = 10;
  var paddleWidth = 75;
  var paddleX = (canvas.width-paddleWidth)/2;
  //  variables que nos dirán si se ha pulsado un botón., Las dos las inicializamos con el valor false porque al principio no están pulsados los botones.
  var rightPressed = false;
  var leftPressed = false;

  var brickRowCount = 5;
  var brickColumnCount = 3;
  var brickWidth = 75;
  var brickHeight = 20;
  var brickPadding = 10;
  var brickOffsetTop = 30;
  var brickOffsetLeft = 30;

  var score = 0;
  var lives = 3;

  // ------------------------------FUNCIONES
  // Guardaremos nuestros ladrillos en una matriz bidimensional que contendrá las columnas (c) de los ladrillos. Cada columna contendrá, a su vez, toda la fila (r) de ladrillos. Cada ladrillo se va a representar con un objeto con las posiciones "x" e "y" en las que se dibujará.
      var bricks = [];
      for(c=0; c<brickColumnCount; c++) {
          bricks[c] = [];
          for(r=0; r<brickRowCount; r++) {
            bricks[c][r] = { x: 0, y: 0, status: 1 };
          }
      }
      // detectar movimiento del mouse
      document.addEventListener("mousemove", mouseMoveHandler, false);
      // Para "escuchar" las pulsaciones de las teclas necesitamos definir dos "escuchadores de eventos" (event listeners)
      document.addEventListener("keydown", keyDownHandler, false);
      document.addEventListener("keyup", keyUpHandler, false);

      // obtner cordenas del puntero: En esta función calculamos un valor relativeX, que es la posición horizontal del ratón en el "viewport" (e.clientX), menos la distancia entre el borde izquierdo del terreno de juego y el borde izquierdo del "viewport" (canvas.offsetLeft).
      function mouseMoveHandler(e) {
        var relativeX = e.clientX - canvas.offsetLeft;
        if(relativeX > 0 && relativeX < canvas.width) {
            paddleX = relativeX - paddleWidth/2;
        }
      }
      // Cuando ocurra el evento keydown al pulsar cualquier tecla del teclado, la función keyDownHandler() se ejecutará. Cuando se liberará la tecla pulsada, se ejecutará la función keyUpHandler()
      function keyDownHandler(e) {
        if(e.keyCode == 39) {
          rightPressed = true;
        }
        else if(e.keyCode == 37) {
          leftPressed = true;
        }
      }
      function keyUpHandler(e) {
          if(e.keyCode == 39) {
              rightPressed = false;
          }
          else if(e.keyCode == 37) {
              leftPressed = false;
          }
      }

      // funcion para cambiar color de pelota y paleta aleatoriamente al tocar border: http://stackoverflow.com/questions/1484506/ddg#1484514
      function random_color() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
          color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
      }

      function change_color(){
        ctx.fillStyle = random_color();
      }
      // Función que, con un bucle, recorrerá todos los ladrillos y comparará la posición de cada uno con la posición de la bola, cada vez que se dibuje un fotograma. Para que el código sea más legible definiremos la variable "b" que almacenará el objeto ladrillo en cada vuelta de bucle:
      function collisionDetection() {
        for(c=0; c<brickColumnCount; c++) {
            for(r=0; r<brickRowCount; r++) {
                var b = bricks[c][r];
                if(b.status == 1) {
                    if(x > b.x && x < b.x+brickWidth && y > b.y && y < b.y+brickHeight) {
                        dy = -dy;
                        b.status = 0;
                        change_color();
                        // aumentar puntos por 2
                        score++;
                        // mensaje de que has vencido
                        if(score == brickRowCount*brickColumnCount) {
                        // if(score == 4 ) {
                            alert("YOU WIN, CONGRATULATIONS! \n your score is: " + score);
                            document.location.reload();
                        }
                    }
                }
            }
        }
      }
      // código para dibujar pelota
      function drawBall() {
        // el trayecto no es coloreado
          ctx.beginPath();
          ctx.arc(x, y, ballRadius, 0, Math.PI*2);
          ctx.fill();
          ctx.closePath();
      }
      // función que dibujará la paleta en la pantalla
      function drawPaddle() {
        ctx.beginPath();
        ctx.rect(paddleX, canvas.height-paddleHeight, paddleWidth, paddleHeight);
        ctx.fill();
        ctx.closePath();
  }
      // una función para recorrer todos los bloques de la matriz y dibujarlos en la pantalla:
      function drawBricks() {
        for(c=0; c<brickColumnCount; c++) {
            for(r=0; r<brickRowCount; r++) {
                if(bricks[c][r].status == 1) {
                  // calcular en qué posición "x" e "y" se tiene que dibujar cada ladrillo
                   var brickX = (c*(brickWidth+brickPadding))+brickOffsetLeft;
                   var brickY = (r*(brickHeight+brickPadding))+brickOffsetTop;
                   bricks[c][r].x = brickX;
                   bricks[c][r].y = brickY;
                   ctx.beginPath();
                   ctx.rect(brickX, brickY, brickWidth, brickHeight);
                   // colorear aleatoriamente
                   // ctx.fillStyle = change_color();
                   ctx.fill();
                   ctx.closePath();
               }
            }
        }
      }

      function drawScore() {
        ctx.font = "16px Arial";
        // ctx.fillStyle = "#0095DD";
        ctx.fillText("Score: "+score, 8, 20);
      }

      function drawLives() {
          // ctx.font = "16px Arial";
          ctx.fillText("Lives: "+lives, canvas.width-65, 20);
      }
      // jugar
      function draw() {
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        // dibujar ladrillos
        drawBricks();
        // dibujar pelota
        drawBall();
        // dibujar paleta
        drawPaddle();
        // destruir ladrillo
        collisionDetection();
        // mostrar score
        drawScore();

        drawLives();

        //hicimos que la pelota rebotara en las paredes:
        if(x + dx > canvas.width-ballRadius || x + dx < ballRadius) {
          // invertir valores significa "rebotar"
          dx = -dx;
          // cambiar color
          change_color();
        }

        if( y + dy < ballRadius) {
          dy = -dy;
          // cambiar color
          change_color();
          // detectar la colisión de la bola y la paleta para que pueda rebotar, volviendo hacia la zona de juego.
        } else if(y + dy > canvas.height-ballRadius) {
          // si el centro de la bola está entre los límites izquierdo y derecho de la paleta.
          if(x > paddleX && x < paddleX + paddleWidth) {

            // aumentar velozidad
            dy += 1;


            // rebotar
            dy = -dy;

          }
          // activará el estado de "final de juego" cuando la pelota colisione con el borde inferior del terreno de juego
          else {
            lives--;
            if(!lives) {
                alert("GAME OVER");
                document.location.reload();
            }
            else {
                x = canvas.width/2;
                y = canvas.height-30;
                dx = 2;
                dy = -2;
                paddleX = (canvas.width-paddleWidth)/2;
            }
          }
        }

        x += dx;
        y += dy;
        // si flecha derecha es apretada y se mantiene dentro del lienzo
        if(rightPressed && paddleX < canvas.width-paddleWidth) {
          // moverse a la derecha con una velozidad...
          paddleX += 7;
        }
        else if(leftPressed && paddleX > 0) {
          paddleX -= 7;
        }
        // refrescar la imagen, llamandose así mismo
        requestAnimationFrame(draw);

      };
      //  La función draw() se ejecutará dentro de setInterval cada 10 milisegundos. esto puede hacer que la perlota vaya más rápido si se vuelve a implementar
      draw();
      // intervalo para cambiar fondo del canva
      setInterval(function(){
        // cambiar color de fondo aleatoriamente
        canvas.style.backgroundColor = random_color();
        }, 1000
      );
//GAME FUNCION END's
};

// iniciar juego
game();

app/views/users/substance.html.erb
      <br>
      <div class="wrap">
      </div>
      <div class="wrap">
        <div class="content ">
          <br>
          <div id="messages">
            <%= render 'messages/index'%>
          </div>

      </div>
    </div>
    <!-- vistas modales -->

    <!-- <script>
      %= render :partial => 'users/index.js'%
    </script> -->

app/views/users/user_log.js.erb
// limpiar lista de errores
$("ul.errors").html("");
// si no hay usuario con esos datos
<% if @user == nil %>
  //anexar en la vista modal el msj:
  $(".errors").append("<p> No usuario con esos datos </p>");
  // si no hay errores
<% else %>

  // mostrar mensajes, botones y deslogearse
  $("#messages").show();
  $("#buttons").show();
  $("#salir").show();
  // ocultar la vista modal de registro
  $("#log-modal").modal("hide");
  // ocultar botones de login y signup y fb
  $("#access").hide();
<% end %>